name: Build and Publish Docker Image

on:
  workflow_dispatch:
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Variables
        id: get-variables
        run: |
          echo ::set-output name=version::${GITHUB_REF#refs/tags/}
          echo ::set-output name=gh-username-lower::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')

      - name: Build and push Image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ steps.get-variables.outputs.gh-username-lower }}/libretranslate:${{ env.TAG }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            with_models=true
            models=ar-en,az-en,ca-en,zh-en,cs-en,da-en,nl-en,eo-en,fi-en,fr-en,de-en,el-en,he-en,hi-en,hu-en,id-en,ga-en,it-en,ja-en,ko-en,fa-en,pl-en,pt-en,ru-en,sk-en,es-en,sv-en,tr-en,uk-en
        env:
          TAG: ${{ startsWith(github.ref, 'refs/tags/') && steps.get-variables.outputs.version || 'latest' }}
